// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Q0W2KPWPUJj6k4CpZWnPweJ_YFeHBMM',
    appId: '1:49107974348:web:d18a93aa2b50a599b66a69',
    messagingSenderId: '49107974348',
    projectId: 'hair-salon-c9251',
    authDomain: 'hair-salon-c9251.firebaseapp.com',
    storageBucket: 'hair-salon-c9251.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUpK1azhqO5r8T0lRYek65xB5wYYtykA',
    appId: '1:49107974348:android:6b3c7d19bb3bc5c8b66a69',
    messagingSenderId: '49107974348',
    projectId: 'hair-salon-c9251',
    storageBucket: 'hair-salon-c9251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqbwsy3GEqhwaFrKN6H3nq5vR3lJOdyc',
    appId: '1:49107974348:ios:82db830681e6d434b66a69',
    messagingSenderId: '49107974348',
    projectId: 'hair-salon-c9251',
    storageBucket: 'hair-salon-c9251.appspot.com',
    iosBundleId: 'com.exampleproj.hairSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuqbwsy3GEqhwaFrKN6H3nq5vR3lJOdyc',
    appId: '1:49107974348:ios:f0beb0e78784d82eb66a69',
    messagingSenderId: '49107974348',
    projectId: 'hair-salon-c9251',
    storageBucket: 'hair-salon-c9251.appspot.com',
    iosBundleId: 'com.exampleproj.hairSalon.RunnerTests',
  );
}
